import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';

// The full documentation concatenated into one Markdown file for LLMs, a
// companion to the hand-written /llms.txt. Served on-demand so the response
// keeps its `text/markdown` content type (a prerendered `.txt` asset would be
// served as text/plain by Cloudflare).
//
// Generated by hand rather than with the starlight-llms-txt plugin: that plugin
// hardcodes /llms.txt and its statically-emitted file wins over any user route,
// so it cannot coexist with a manually authored /llms.txt (the whole point).
export const prerender = false;

// Reading order that mirrors the docs sidebar (astro.config.mjs).
const SECTION_ORDER = ['getting-started', 'guides', 'integrations', 'reference'];

/** Content-directory names of every non-English locale, baked in at build. */
const LOCALE_DIRS: readonly string[] = __LOCALE_DIRS__;

function rank(id: string): number {
  // The docs landing page first.
  if (id === 'docs' || id === 'docs/index') return -1;
  const section = id.split('/')[1] ?? '';
  const i = SECTION_ORDER.indexOf(section);
  return i === -1 ? SECTION_ORDER.length : i;
}

// The docs index is `.mdx`; its raw body carries MDX `import`/`export`
// statements and JSX component blocks (e.g. `<CardGrid>` / `<LinkCard />`)
// that are noise in a plain-text dump. Drop lines that are purely such syntax;
// the `.md` pages are unaffected.
function stripMdx(body: string): string {
  return body
    .split('\n')
    .filter((line) => {
      const t = line.trim();
      if (/^(import|export)\s/.test(t)) return false;
      // A line that is only a JSX component tag: <Name ...>, </Name>, <Name />.
      if (/^<\/?[A-Z][A-Za-z0-9]*(\s[^>]*)?\/?>$/.test(t)) return false;
      return true;
    })
    .join('\n');
}

export const GET: APIRoute = async ({ site }) => {
  const entries = await getCollection('docs', (entry) => {
    const { id } = entry;
    // English (root locale) only — skip the translated locale trees. The
    // prefixes come from the one locale table in scripts/i18n/locales.mjs via
    // astro.config.mjs; enumerating them here is how a newly added language
    // silently got concatenated onto the English docs instead of being left
    // out of this file.
    if (LOCALE_DIRS.some((dir) => id.startsWith(`${dir}/`))) return false;
    // Skip the auto-generated TypeScript API reference: it is verbose, derived
    // from JSDoc, and better consumed from the types themselves. The
    // hand-written /llms.txt already links to the rendered API reference.
    if (id.startsWith('docs/reference/api')) return false;
    return true;
  });

  entries.sort((a, b) => {
    const diff = rank(a.id) - rank(b.id);
    return diff !== 0 ? diff : a.id.localeCompare(b.id);
  });

  const origin = site ? site.origin : '';

  const header =
    `# test-proxy-recorder — full documentation\n\n` +
    `The complete text of the documentation at ${origin}/docs/, concatenated for LLMs. ` +
    `For a condensed, agent-first reference (Intent skills + quick setup), see ${origin}/llms.txt.\n`;

  const sections = entries.map((entry) => {
    const slug = entry.id.replace(/\/index$/, '');
    const url = `${origin}/${slug}/`;
    const title = entry.data.title ?? slug;
    return `\n\n---\n\n# ${title}\n\nSource: ${url}\n\n${stripMdx(entry.body ?? '')}`;
  });

  return new Response(header + sections.join(''), {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
};
