---
engines:
languages:
  css:
    enabled: false
exclude_paths:
  - "dist"
  - "dist/*"
  - "dist/**"
  - "dist/**/*"
  - "tests"
  - "tests/*"
  - "tests/**"
  - "tests/**/*"
  - ".github"
  - ".github/*"
  - ".github/**"
  - ".github/**/*"
  - ".vscode"
  - ".vscode/*"
  - ".vscode/**"
  - ".vscode/**/*"
  - "dependabot.yml"
  - ".codacy.yml"
  - "package.json"
  - "package-lock.json"
  - ".eslintrc.json"
  - "tsconfig.json"
  - "tsconfig.*.json"
  - "**.test.ts"
  - "*.test.ts"
  - "**.test.tsx"
  - "*.test.tsx"
  - "**.spec.ts"
  - "*.spec.ts"
  - "**.spec.tsx"
  - "**.config.*"
  - "*.config.*"
  - "*.env.ts"
  - "**.md"
  - "*.md"
include_paths:
  - "src/"
  - "src/*"
  - "src/**"
  - "src/**/*"
