import path from 'node:path';

// Gitignored (see root .gitignore). Regenerated by the `setup` project on every
// run. Playwright runs from the app root, so resolve relative to cwd.
export const authStatePath = path.resolve(process.cwd(), 'e2e', 'auth-state.json');
