import { defineConfig } from 'test-proxy-recorder';

// Generated by `test-proxy-recorder init`.
// Auto-discovered when you run `test-proxy-recorder` with no arguments.
// CLI flags always override the values set here.
export default defineConfig({
  // Backend the proxy records against. Point your app's API base URL here too.
  target: 'http://localhost:9999',

  // Port the proxy listens on. Matches the Playwright client default
  // (override both with the TEST_PROXY_RECORDER_PORT env var).
  port: 8100,

  // Where .mock.json recordings are written, relative to this file.
  // Commit this directory — CI replays from it.
  recordingsDir: './rec',

  // Secrets are redacted automatically (Authorization / Cookie / Set-Cookie).
  // Uncomment to redact extra headers or tokens embedded in bodies.
  // redaction: {
  //   headers: ['x-api-key'],
  //   bodyPatterns: [/sk_live_\w+/g],
  //   allowCookies: ['theme'],
  // },
});
