import { spawnSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

// The files `init` writes are compiled with the user's own settings, so they
// must pass strict ones, exactOptionalPropertyTypes included, against the
// published type declarations.
const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  '..',
);
const PACKAGE_DIR = path.join(REPO_ROOT, 'packages', 'test-proxy-recorder');
const CLI_BIN = path.join(PACKAGE_DIR, 'dist', 'proxy.js');
const TSC = path.join(PACKAGE_DIR, 'node_modules', '.bin', 'tsc');

let projectDir: string;
let viteDir: string;

beforeAll(() => {
  if (!existsSync(CLI_BIN)) {
    const build = spawnSync('pnpm', ['--filter', 'test-proxy-recorder', 'build'], {
      cwd: REPO_ROOT,
      stdio: 'inherit',
    });
    expect(build.status).toBe(0);
  }
  // Inside the package, with no package.json of its own: `test-proxy-recorder`
  // then resolves to the package's built types and `@playwright/test` to its
  // installed copy.
  projectDir = mkdtempSync(path.join(PACKAGE_DIR, '.tmp-generated-types-'));
  const init = spawnSync('node', [CLI_BIN, 'init', '--no-install'], {
    cwd: projectDir,
    encoding: 'utf8',
  });
  expect(init.status, init.stderr).toBe(0);

  // The E2E_BUILD variant needs dev/build/preview scripts, and a package.json
  // here would break the self-resolution above, so it is generated elsewhere.
  viteDir = mkdtempSync(path.join(os.tmpdir(), 'tpr-generated-vite-'));
  writeFileSync(
    path.join(viteDir, 'package.json'),
    JSON.stringify({
      scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    }),
  );
  const viteInit = spawnSync('node', [CLI_BIN, 'init', '--no-install'], {
    cwd: viteDir,
    encoding: 'utf8',
  });
  expect(viteInit.status, viteInit.stderr).toBe(0);
  copyFileSync(
    path.join(viteDir, 'playwright.config.ts'),
    path.join(projectDir, 'playwright.build.config.ts'),
  );

  writeFileSync(
    path.join(projectDir, 'tsconfig.json'),
    JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        exactOptionalPropertyTypes: true,
        noUncheckedIndexedAccess: true,
        noEmit: true,
        skipLibCheck: true,
        types: ['node'],
      },
      include: ['**/*.ts'],
    }),
  );
});

afterAll(() => {
  if (projectDir) rmSync(projectDir, { recursive: true, force: true });
  if (viteDir) rmSync(viteDir, { recursive: true, force: true });
});

describe('files generated by init', () => {
  it('include the E2E_BUILD switch when the project has a preview script', () => {
    expect(
      readFileSync(path.join(projectDir, 'playwright.build.config.ts'), 'utf8'),
    ).toContain('const IS_BUILD = Boolean(process.env.E2E_BUILD);');
  });

  it('type-check under strict settings', () => {
    const tsc = spawnSync(TSC, ['-p', projectDir], { encoding: 'utf8' });

    expect(tsc.stdout + tsc.stderr).toBe('');
    expect(tsc.status).toBe(0);
  });
});
