import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { Command } from 'commander';

/** Config file the scaffold writes; auto-discovered by the proxy at startup. */
export const CONFIG_FILENAME = 'test-proxy-recorder.config.ts';

/** Playwright config filenames we look for, in resolution order. */
export const PLAYWRIGHT_CONFIG_NAMES = [
  'playwright.config.ts',
  'playwright.config.mts',
  'playwright.config.cts',
  'playwright.config.js',
  'playwright.config.mjs',
  'playwright.config.cjs',
];

// A non-3000 default: 3000 is the conventional Next.js *app* port, not the
// backend the proxy records against.
const DEFAULT_TARGET = 'http://localhost:3002';
const DEFAULT_PORT = 8100;
const DEFAULT_DIR = './e2e/recordings';

/** Resolved inputs for a scaffold run. */
export interface InitOptions {
  /** Backend API URL the proxy forwards to while recording. */
  target: string;
  /** Port the proxy listens on (kept in sync with the Playwright client default). */
  port: number;
  /** Directory recordings are written to, relative to the config file. */
  dir: string;
  /** Overwrite existing files / script keys instead of leaving them untouched. */
  force: boolean;
  /** Run the Playwright CLI when Playwright is missing (disable with --no-install). */
  install: boolean;
}

/** What happened to a single scaffolded file or package.json entry. */
export type ScaffoldStatus = 'created' | 'updated' | 'skipped';

export interface ScaffoldAction {
  /** Path relative to the project root. */
  relPath: string;
  status: ScaffoldStatus;
  /** Human-readable reason, shown for skips/updates. */
  detail?: string;
}

/** Outcome of {@link runInit}: one entry per file/edit it considered. */
export interface InitResult {
  actions: ScaffoldAction[];
}

// --- file templates (pure renderers) ---------------------------------------

/**
 * Render `test-proxy-recorder.config.ts`. The generated file mirrors the
 * documented config shape: a `defineConfig` default export with the resolved
 * target/port/dir filled in and the optional redaction block left commented out.
 */
export function renderConfig(options: InitOptions): string {
  return `import { defineConfig } from 'test-proxy-recorder';

// Generated by \`test-proxy-recorder init\`.
// Auto-discovered when you run \`test-proxy-recorder\` with no arguments.
// CLI flags always override the values set here.
export default defineConfig({
  // Backend the proxy records against. Point your app's API base URL here too.
  target: '${options.target}',

  // Port the proxy listens on. Matches the Playwright client default
  // (override both with the TEST_PROXY_RECORDER_PORT env var).
  port: ${options.port},

  // Where .mock.json recordings are written, relative to this file.
  // Commit this directory — CI replays from it.
  recordingsDir: '${options.dir}',

  // Secrets are redacted automatically (Authorization / Cookie / Set-Cookie).
  // Uncomment to redact extra headers or tokens embedded in bodies.
  // redaction: {
  //   headers: ['x-api-key'],
  //   bodyPatterns: [/sk_live_\\w+/g],
  //   allowCookies: ['theme'],
  // },
});
`;
}

/** Render a fresh `playwright.config.ts` wired to the proxy's control endpoint. */
export function renderPlaywrightConfig(options: InitOptions): string {
  return `import { defineConfig } from '@playwright/test';

// Generated by \`test-proxy-recorder init\`.
export default defineConfig({
  testDir: './e2e',
  // Resets the proxy to transparent mode after the run.
  globalTeardown: './e2e/global-teardown.ts',
  // Boots the recorder; it reads target/port/dir from
  // test-proxy-recorder.config.ts. Health-check hits /__control, which is
  // always available (the proxy root forwards to your backend).
  webServer: {
    command: 'test-proxy-recorder',
    url: 'http://localhost:${options.port}/__control',
    reuseExistingServer: true,
    timeout: 15_000,
  },
});
`;
}

/** Render the per-test proxy fixture (`e2e/fixtures.ts`). */
export function renderFixtures(): string {
  return String.raw`import { test as base, type Page } from '@playwright/test';
import { playwrightProxy } from 'test-proxy-recorder';

// External domains the browser calls directly (auth, CDN, analytics, ...).
// Server-side fetches through the proxy are recorded automatically — this is
// only for browser-side requests that never touch the proxy.
const CLIENT_SIDE_URL = /api\.example\.com/;

// Change to 'record' to hit the real API and refresh recordings, then switch
// back to 'replay' and commit. Record with a single worker (--workers 1).
const MODE = 'replay' as const;

export const test = base.extend<{ page: Page }>({
  page: async ({ context }, use, testInfo) => {
    const page = await context.newPage();
    await playwrightProxy.before(page, testInfo, MODE, { url: CLIENT_SIDE_URL });
    await use(page);
  },
});

export { expect } from '@playwright/test';
`;
}

/** Render the global teardown (`e2e/global-teardown.ts`). */
export function renderTeardown(): string {
  return `import { playwrightProxy } from 'test-proxy-recorder';

// Runs once after the whole suite — resets the proxy to transparent mode and
// redacts secrets from the recorded .har files (HAR redaction happens here, not
// per-test). Do NOT call teardown() per-test (afterAll): it flips the global
// mode and breaks parallel replay.
export default async function globalTeardown() {
  await playwrightProxy
    .teardown()
    .catch((err) => console.warn('test-proxy-recorder teardown', err));
}
`;
}

/** Next.js project info detected from `package.json`, or null when not Next.js. */
export interface NextjsInfo {
  /** Major version parsed from the declared range, or null when not numeric. */
  major: number | null;
  /**
   * Next.js 16+ renamed the middleware entry to `proxy.ts` (exported `proxy`);
   * 15 and earlier use `middleware.ts` (exported `middleware`). When the version
   * is unknown (e.g. `next: "latest"`) we assume the current convention.
   */
  useProxyConvention: boolean;
}

/** Pull the leading major version out of a semver range (`^16.2.4` → 16). */
function parseMajor(range: string): number | null {
  const match = range.match(/(\d+)/);
  return match ? Number.parseInt(match[1], 10) : null;
}

/**
 * Detect a Next.js project from its declared `next` dependency. Returns the
 * major version (when numeric) and which middleware-file convention applies, or
 * null when the project does not depend on Next.js.
 */
export function detectNextjs(cwd: string): NextjsInfo | null {
  const pkgPath = path.join(cwd, 'package.json');
  if (!existsSync(pkgPath)) return null;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as PackageJson;
    const range = pkg.dependencies?.next ?? pkg.devDependencies?.next;
    if (!range) return null;
    const major = parseMajor(range);
    return { major, useProxyConvention: major === null || major >= 16 };
  } catch {
    return null;
  }
}

/**
 * Render the Next.js middleware that propagates the recording-session header
 * onto server-side fetches, so SSR traffic is recorded and replayed. The file
 * name and exported function follow the version convention (see {@link NextjsInfo}).
 */
export function renderNextMiddleware(info: NextjsInfo): string {
  const fnName = info.useProxyConvention ? 'proxy' : 'middleware';
  const fileLabel = info.useProxyConvention
    ? 'proxy.ts — Next.js 16+ middleware entry point'
    : 'middleware.ts — Next.js 15 middleware entry point';
  return `// ${fileLabel}. Generated by \`test-proxy-recorder init\`.
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { setNextProxyHeaders } from 'test-proxy-recorder/nextjs';

export function ${fnName}(request: NextRequest) {
  const response = NextResponse.next();
  // Copies the recording-session header onto server-side fetches so SSR
  // traffic is recorded/replayed. No-op in production.
  setNextProxyHeaders(request, response);
  return response;
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
};
`;
}

/** Scripts merged into the project's package.json. */
export function scaffoldScripts(): Record<string, string> {
  return {
    proxy: 'test-proxy-recorder',
    'proxy:reset': 'test-proxy-recorder reset',
    'test:e2e': 'playwright test',
    'test:e2e:record': 'playwright test --workers 1 --ui',
  };
}

/**
 * Inject a `webServer` (pointing at the proxy's control endpoint) and a
 * `globalTeardown` into an existing Playwright config's source. Pure string
 * transform — easy to unit-test and conservative: it bails (rather than risk
 * producing a broken or duplicate-keyed config) when it cannot safely edit.
 */
export function injectProxyIntoConfig(
  source: string,
  options: InitOptions,
): { contents: string; changed: boolean; reason?: string } {
  if (source.includes('test-proxy-recorder')) {
    return {
      contents: source,
      changed: false,
      reason: 'already references test-proxy-recorder',
    };
  }
  if (/\bwebServer\s*:/.test(source)) {
    return {
      contents: source,
      changed: false,
      reason: 'already defines webServer — add the proxy command manually',
    };
  }

  // Insert right after the config object opens: `defineConfig({` or a bare
  // `export default {`.
  const opener =
    source.match(/defineConfig\s*\(\s*\{/) ??
    source.match(/export\s+default\s*\{/);
  if (opener?.index === undefined) {
    return {
      contents: source,
      changed: false,
      reason: 'could not locate the config object',
    };
  }

  const hasTeardown = /\bglobalTeardown\s*:/.test(source);
  const teardownLine = hasTeardown
    ? ''
    : `\n  globalTeardown: './e2e/global-teardown.ts',`;
  const block =
    `\n  // Added by test-proxy-recorder init` +
    `\n  webServer: {` +
    `\n    command: 'test-proxy-recorder',` +
    `\n    url: 'http://localhost:${options.port}/__control',` +
    `\n    reuseExistingServer: true,` +
    `\n    timeout: 15_000,` +
    `\n  },${teardownLine}`;

  const at = opener.index + opener[0].length;
  const contents = source.slice(0, at) + block + source.slice(at);
  return { contents, changed: true };
}

// --- filesystem orchestration ----------------------------------------------

/** Locate an existing Playwright config in `cwd`, or null when none exists. */
export function findPlaywrightConfig(cwd: string): string | null {
  for (const name of PLAYWRIGHT_CONFIG_NAMES) {
    const candidate = path.join(cwd, name);
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

/**
 * Write `contents` to `relPath` under `cwd`, creating parent dirs. Existing
 * files are left untouched unless `force` is set, so re-running `init` is safe.
 */
function writeFile(
  cwd: string,
  relPath: string,
  contents: string,
  force: boolean,
): ScaffoldAction {
  const absPath = path.join(cwd, relPath);
  const overwritten = existsSync(absPath);
  if (overwritten && !force) {
    return { relPath, status: 'skipped', detail: 'already exists' };
  }
  mkdirSync(path.dirname(absPath), { recursive: true });
  writeFileSync(absPath, contents, 'utf8');
  return {
    relPath,
    status: 'created',
    detail: overwritten ? 'overwritten' : undefined,
  };
}

/**
 * Wire Playwright up: edit an existing config in place, or write a fresh default
 * one when none exists. Never touches a config it cannot safely edit.
 */
function scaffoldPlaywright(cwd: string, options: InitOptions): ScaffoldAction {
  const existing = findPlaywrightConfig(cwd);
  if (!existing) {
    return writeFile(
      cwd,
      'playwright.config.ts',
      renderPlaywrightConfig(options),
      options.force,
    );
  }

  const relPath = path.relative(cwd, existing) || path.basename(existing);
  const source = readFileSync(existing, 'utf8');
  const { contents, changed, reason } = injectProxyIntoConfig(source, options);
  if (!changed) {
    return { relPath, status: 'skipped', detail: reason };
  }
  writeFileSync(existing, contents, 'utf8');
  return {
    relPath,
    status: 'updated',
    detail: 'added webServer + globalTeardown',
  };
}

/** Middleware/proxy entry files Next.js recognizes, in root and `src/`. */
const NEXT_MIDDLEWARE_NAMES = [
  'proxy.ts',
  'proxy.js',
  'middleware.ts',
  'middleware.js',
  'src/proxy.ts',
  'src/proxy.js',
  'src/middleware.ts',
  'src/middleware.js',
];

/** True when `relPath` is a Next.js middleware/proxy entry file. */
export function isNextMiddlewareFile(relPath: string): boolean {
  return NEXT_MIDDLEWARE_NAMES.includes(relPath.split(path.sep).join('/'));
}

/** Find an existing Next.js middleware/proxy entry file, or null when none. */
function findExistingNextMiddleware(cwd: string): string | null {
  for (const name of NEXT_MIDDLEWARE_NAMES) {
    if (existsSync(path.join(cwd, name))) return name;
  }
  return null;
}

/**
 * Scaffold the Next.js middleware that forwards the recording-session header on
 * SSR fetches. Conservative: if the project already has any middleware/proxy
 * file we leave it alone (the user owns it) and the next-steps output tells them
 * the one line to add, rather than risk clobbering their logic.
 */
function scaffoldNextMiddleware(
  cwd: string,
  info: NextjsInfo,
  force: boolean,
): ScaffoldAction {
  const existing = findExistingNextMiddleware(cwd);
  if (existing && !force) {
    return {
      relPath: existing,
      status: 'skipped',
      detail: 'middleware exists — add setNextProxyHeaders() yourself',
    };
  }
  const target = info.useProxyConvention ? 'proxy.ts' : 'middleware.ts';
  return writeFile(cwd, target, renderNextMiddleware(info), force);
}

/** Detect the indentation used by an existing JSON file (defaults to 2 spaces). */
function detectIndent(source: string): string {
  const match = source.match(/\n([ \t]+)"/);
  return match ? match[1] : '  ';
}

/** Script the original `dev` command is moved to when wrapping it. */
const DEV_APP_SCRIPT = 'dev:app';

/** How a package manager runs a named script (`pnpm proxy`, `npm run proxy`). */
function runScriptPrefix(pm: PackageManager): string {
  // pnpm/yarn run scripts as `pnpm <script>`; npm/bun need `run`.
  return pm === 'pnpm' || pm === 'yarn' ? pm : `${pm} run`;
}

/**
 * Apply `scripts` onto `existing` in place, honouring `force`. Returns which
 * keys were newly added and which were left as the user already had them.
 */
function mergeScripts(
  existing: Record<string, string>,
  scripts: Record<string, string>,
  force: boolean,
): { added: string[]; skipped: string[] } {
  const added: string[] = [];
  const skipped: string[] = [];
  for (const [name, command] of Object.entries(scripts)) {
    const conflicts = existing[name] !== undefined && !force;
    (conflicts ? skipped : added).push(name);
    if (!conflicts) existing[name] = command;
  }
  return { added, skipped };
}

/**
 * Wrap an existing `dev` script so it runs the proxy alongside the app: the
 * original command is moved to `dev:app` and `dev` becomes a `concurrently`
 * invocation. Idempotent and conservative — does nothing when there is no `dev`
 * script, when it already runs the proxy, or when `dev:app` is taken.
 */
function wrapDevScript(
  scripts: Record<string, string>,
  pm: PackageManager,
): boolean {
  const dev = scripts.dev;
  if (dev === undefined) return false;
  if (dev.includes('test-proxy-recorder') || dev.includes('concurrently')) {
    return false;
  }
  if (scripts[DEV_APP_SCRIPT] !== undefined) return false;

  const run = runScriptPrefix(pm);
  scripts[DEV_APP_SCRIPT] = dev;
  scripts.dev = `concurrently --kill-others "${run} proxy" "${run} ${DEV_APP_SCRIPT}"`;
  return true;
}

/** Add `concurrently` as a devDependency when the project lacks it. */
function ensureConcurrentlyDep(pkg: {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}): boolean {
  if (
    pkg.dependencies?.concurrently !== undefined ||
    pkg.devDependencies?.concurrently !== undefined
  ) {
    return false;
  }
  pkg.devDependencies ??= {};
  pkg.devDependencies.concurrently = '^9.0.0';
  return true;
}

interface PackageJson {
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

/**
 * Merge the scaffold scripts into an existing package.json without clobbering
 * existing keys (unless `force`), and wrap the project's `dev` script so it runs
 * the proxy too. When there is no package.json — e.g. the user has not
 * initialized one yet — the edit is skipped rather than inventing one.
 */
function updatePackageScripts(
  cwd: string,
  scripts: Record<string, string>,
  force: boolean,
): ScaffoldAction {
  const relPath = 'package.json';
  const absPath = path.join(cwd, relPath);

  if (!existsSync(absPath)) {
    return { relPath, status: 'skipped', detail: 'no package.json found' };
  }

  const source = readFileSync(absPath, 'utf8');
  const pkg = JSON.parse(source) as PackageJson;
  pkg.scripts ??= {};

  const { added, skipped } = mergeScripts(pkg.scripts, scripts, force);
  const devWrapped = wrapDevScript(pkg.scripts, detectPackageManager(cwd));
  if (devWrapped) ensureConcurrentlyDep(pkg);

  if (added.length === 0 && !devWrapped) {
    return {
      relPath,
      status: 'skipped',
      detail: `scripts already present (${skipped.join(', ')})`,
    };
  }

  const indent = detectIndent(source);
  const trailingNewline = source.endsWith('\n') ? '\n' : '';
  writeFileSync(absPath, JSON.stringify(pkg, null, indent) + trailingNewline);

  return {
    relPath,
    status: 'updated',
    detail: describeEdit(added, skipped, devWrapped),
  };
}

/** Build the human-readable summary of a package.json edit. */
function describeEdit(
  added: string[],
  skipped: string[],
  devWrapped: boolean,
): string {
  const parts: string[] = [];
  if (added.length > 0) parts.push(`added ${added.join(', ')}`);
  if (skipped.length > 0) parts.push(`kept existing ${skipped.join(', ')}`);
  if (devWrapped) parts.push(`wrapped dev (original → ${DEV_APP_SCRIPT})`);
  return parts.join('; ');
}

/**
 * Run the full scaffold: config file, Playwright config (created or edited in
 * place), e2e fixture + teardown, and package.json scripts. Pure filesystem work
 * — the optional Playwright CLI install lives in {@link initCommand}. Every step
 * is non-destructive.
 */
export function runInit(
  options: InitOptions,
  cwd: string = process.cwd(),
): InitResult {
  const actions: ScaffoldAction[] = [
    writeFile(cwd, CONFIG_FILENAME, renderConfig(options), options.force),
    scaffoldPlaywright(cwd, options),
    writeFile(cwd, 'e2e/fixtures.ts', renderFixtures(), options.force),
    writeFile(cwd, 'e2e/global-teardown.ts', renderTeardown(), options.force),
    updatePackageScripts(cwd, scaffoldScripts(), options.force),
  ];

  // Next.js makes server-side fetches that need the recording-session header
  // propagated; scaffold the middleware that does it when we detect Next.js.
  const nextjs = detectNextjs(cwd);
  if (nextjs) {
    actions.push(scaffoldNextMiddleware(cwd, nextjs, options.force));
  }

  return { actions };
}

// --- Playwright CLI install (side-effecting) -------------------------------

/** True when `@playwright/test` is installed or declared in the project. */
export function playwrightInstalled(cwd: string): boolean {
  if (existsSync(path.join(cwd, 'node_modules', '@playwright', 'test'))) {
    return true;
  }
  const pkgPath = path.join(cwd, 'package.json');
  if (!existsSync(pkgPath)) return false;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    return Boolean(
      pkg.dependencies?.['@playwright/test'] ??
        pkg.devDependencies?.['@playwright/test'],
    );
  } catch {
    return false;
  }
}

type PackageManager = 'pnpm' | 'yarn' | 'bun' | 'npm';

/** Best-effort package-manager detection from the env / lockfiles. */
export function detectPackageManager(cwd: string): PackageManager {
  const ua = process.env.npm_config_user_agent ?? '';
  if (ua.startsWith('pnpm') || existsSync(path.join(cwd, 'pnpm-lock.yaml'))) {
    return 'pnpm';
  }
  if (ua.startsWith('yarn') || existsSync(path.join(cwd, 'yarn.lock'))) {
    return 'yarn';
  }
  if (ua.startsWith('bun') || existsSync(path.join(cwd, 'bun.lockb'))) {
    return 'bun';
  }
  return 'npm';
}

/** The `create playwright` invocation for a package manager (non-interactive). */
export function playwrightCreateCommand(pm: PackageManager): {
  cmd: string;
  args: string[];
} {
  // `--quiet` runs create-playwright with its defaults (TypeScript, ./tests,
  // no GitHub Actions). Limit to chromium to keep the browser download small.
  const flags = ['--quiet', '--browser=chromium'];
  switch (pm) {
    case 'pnpm': {
      return { cmd: 'pnpm', args: ['create', 'playwright', '--', ...flags] };
    }
    case 'yarn': {
      return { cmd: 'yarn', args: ['create', 'playwright', ...flags] };
    }
    case 'bun': {
      return { cmd: 'bun', args: ['create', 'playwright', ...flags] };
    }
    default: {
      return {
        cmd: 'npm',
        args: ['init', 'playwright@latest', '--', ...flags],
      };
    }
  }
}

/**
 * When there is no Playwright config and Playwright is not installed, run the
 * package manager's `create playwright` scaffolder so the project ends up with a
 * real Playwright setup. Best-effort: a failure (offline, prompt, missing PM)
 * just falls back to the bundled default config written by {@link runInit}.
 */
function maybeInstallPlaywright(options: InitOptions, cwd: string): void {
  if (!options.install) return;
  if (findPlaywrightConfig(cwd)) return; // we'll edit the existing config
  if (playwrightInstalled(cwd)) return; // installed; we'll write a config

  const { cmd, args } = playwrightCreateCommand(detectPackageManager(cwd));
  console.log(
    `No Playwright config found and Playwright is not installed.\n` +
      `Running \`${cmd} ${args.join(' ')}\` (pass --no-install to skip)...`,
  );

  let failed = true;
  try {
    const result = spawnSync(cmd, args, { cwd, stdio: 'inherit' });
    failed = result.status !== 0;
  } catch {
    failed = true;
  }

  if (failed) {
    console.warn(
      'Playwright CLI scaffold did not complete — writing a default ' +
        'playwright.config.ts instead. Install Playwright with ' +
        '`npm install -D @playwright/test`.',
    );
  }
}

// --- CLI wiring ------------------------------------------------------------

/**
 * Parse `init` subcommand arguments. `argv` is the raw process argv with the
 * leading `node`, script, and `init` token already removed by the caller.
 */
export function parseInitArgs(argv: string[]): InitOptions {
  const program = new Command();

  program
    .name('test-proxy-recorder init')
    .description(
      'Scaffold test-proxy-recorder config + Playwright setup in the current directory',
    )
    .argument(
      '[target]',
      'Backend API URL the proxy records against',
      DEFAULT_TARGET,
    )
    .option('-p, --port <number>', 'Proxy port', String(DEFAULT_PORT))
    .option('-d, --dir <path>', 'Recordings directory', DEFAULT_DIR)
    .option(
      '-f, --force',
      'Overwrite existing files and package.json scripts',
      false,
    )
    .option(
      '--no-install',
      'Do not run the Playwright CLI when Playwright is missing',
    )
    .allowExcessArguments(false);

  // `argv` is already stripped to the init-specific tokens; tell commander to
  // treat it as user args (no node/script prefix to skip).
  program.parse(argv, { from: 'user' });

  const target = program.args[0] ?? DEFAULT_TARGET;
  const opts = program.opts<{
    port: string;
    dir: string;
    force: boolean;
    install: boolean;
  }>();

  const port = Number.parseInt(opts.port, 10);
  if (Number.isNaN(port) || port < 1025 || port > 65_535) {
    console.error('Error: Invalid port number. Must be between 1025 and 65535');
    process.exit(1);
  }

  return {
    target,
    port,
    dir: opts.dir,
    force: opts.force,
    install: opts.install,
  };
}

/** Past-tense label shown for each action in the summary. */
const STATUS_LABEL: Record<ScaffoldStatus, string> = {
  created: 'Created',
  updated: 'Updated',
  skipped: 'Skipped',
};

/**
 * Entry point for the `init` subcommand: optionally bootstrap Playwright, run the
 * scaffold, and print a per-file summary plus next steps. A thin, side-effecting
 * shell over the testable `parseInitArgs` / `runInit` pieces.
 */
export function initCommand(argv: string[], cwd: string = process.cwd()): void {
  const options = parseInitArgs(argv);

  maybeInstallPlaywright(options, cwd);

  const { actions } = runInit(options, cwd);

  console.log('');
  for (const action of actions) {
    const label = STATUS_LABEL[action.status];
    const suffix = action.detail ? ` — ${action.detail}` : '';
    console.log(`${label.padEnd(7)} ${action.relPath}${suffix}`);
  }

  printNextSteps(actions, options);
}

/**
 * The one thing `init` can't do for you: route the app's backend calls through
 * the proxy, in dev/test only. Which env var the app reads, and how to scope it
 * to dev, is app-specific — so we print concrete, copy-pasteable guidance.
 */
function backendPointingLines(
  options: InitOptions,
  devWrapped: boolean,
): string[] {
  const proxyUrl = `http://localhost:${options.port}`;
  const lines = [
    "  1. Point your app's backend calls at the proxy — in dev/test only, never in production.",
    `     Set whatever env var your app reads its API base URL from to:  ${proxyUrl}`,
    `     (it talks to ${options.target} directly today; the proxy forwards there while`,
    '      recording and serves recordings on replay.)',
  ];
  const example = devWrapped
    ? `       "dev:app": "API_BASE_URL=${proxyUrl} <your dev command>"`
    : `       API_BASE_URL=${proxyUrl} <your dev/start command>`;
  lines.push(
    '     e.g. (use cross-env to make this work on Windows):',
    example,
  );
  return lines;
}

/**
 * Lines describing the Next.js middleware outcome: a confirmation when we wrote
 * it, or the one line to add by hand when the project already had middleware.
 */
function middlewareLines(actions: ScaffoldAction[]): string[] {
  const mw = actions.find((a) => isNextMiddlewareFile(a.relPath));
  if (!mw) return [];
  if (mw.status === 'skipped') {
    return [
      `  • Next.js middleware already exists (${mw.relPath}) — add this so SSR fetches are recorded:`,
      "       import { setNextProxyHeaders } from 'test-proxy-recorder/nextjs';",
      '       // then inside your middleware: setNextProxyHeaders(request, response);',
    ];
  }
  return [
    `  • Next.js SSR header propagation wired up in ${mw.relPath} (no-op in production).`,
  ];
}

/** Print the "Next steps" block, tailored to what the scaffold actually did. */
function printNextSteps(actions: ScaffoldAction[], options: InitOptions): void {
  const pkgAction = actions.find((a) => a.relPath === 'package.json');
  const pwAction = actions.find((a) =>
    a.relPath.startsWith('playwright.config'),
  );
  const devWrapped = pkgAction?.detail?.includes('wrapped dev') ?? false;

  const step2 =
    pwAction?.status === 'skipped'
      ? `  2. Wire the proxy into your Playwright config (${pwAction.detail}):\n` +
        `       webServer: { command: 'test-proxy-recorder', url: 'http://localhost:${options.port}/__control', reuseExistingServer: true }`
      : "  2. Record: set MODE = 'record' in e2e/fixtures.ts, then run your record script.";

  const step3 =
    pkgAction?.detail === 'no package.json found'
      ? '  3. Add scripts manually: "proxy": "test-proxy-recorder", "test:e2e": "playwright test".'
      : `  3. Switch MODE back to 'replay' and commit ${options.dir}.`;

  console.log('');
  console.log('Next steps:');
  for (const line of backendPointingLines(options, devWrapped)) {
    console.log(line);
  }
  console.log(step2);
  console.log(step3);
  for (const line of middlewareLines(actions)) {
    console.log(line);
  }
  console.log(
    '  • Stuck in record/replay after an interrupted run? Run `test-proxy-recorder reset` (or `proxy:reset`) to return the proxy to transparent mode.',
  );
  if (devWrapped) {
    console.log(
      '  • `dev` now runs the proxy + your app together (install `concurrently` if needed).',
    );
  }
}
