import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { Command } from 'commander';

import { DEFAULT_PROXY_PORT } from './constants.js';

/** Config file the scaffold writes; auto-discovered by the proxy at startup. */
export const CONFIG_FILENAME = 'test-proxy-recorder.config.ts';

/** Playwright config filenames we look for, in resolution order. */
export const PLAYWRIGHT_CONFIG_NAMES = [
  'playwright.config.ts',
  'playwright.config.mts',
  'playwright.config.cts',
  'playwright.config.js',
  'playwright.config.mjs',
  'playwright.config.cjs',
];

// A non-3000 default: 3000 is the conventional Next.js *app* port, not the
// backend the proxy records against.
const DEFAULT_TARGET = 'http://localhost:3002';
const DEFAULT_DIR = './e2e/recordings';
// Shown when the dev port is unknown, with a comment asking to set it.
const PLACEHOLDER_DEV_URL = 'http://localhost:3000';
// Each dev server's default port, by the command `dev` runs. A wrong guess waits
// for a server that never comes, or reuses another app on that port.
const DEV_PORT_BY_COMMAND: Record<string, number> = {
  next: 3000,
  nuxt: 3000,
  nuxi: 3000,
  'react-scripts': 3000,
  ng: 4200,
  astro: 4321,
  vite: 5173,
  'react-router': 5173,
};
// Vite's default preview port; the build gets its own so dev can keep running.
const VITE_PREVIEW_PORT = 4173;
const NEXT_BUILD_PORT = '3100';

/** Resolved inputs for a scaffold run. */
export interface InitOptions {
  /** Backend API URL the proxy forwards to while recording. */
  target: string;
  /** Port the proxy listens on (kept in sync with the Playwright client default). */
  port: number;
  /** Directory recordings are written to, relative to the config file. */
  dir: string;
  /** Overwrite existing files / script keys instead of leaving them untouched. */
  force: boolean;
  /**
   * Run the package manager: the Playwright CLI when Playwright is missing, and
   * an install when init added devDependencies (disable with --no-install).
   */
  install: boolean;
}

/** What happened to a single scaffolded file or package.json entry. */
export type ScaffoldStatus = 'created' | 'updated' | 'skipped';

export interface ScaffoldAction {
  /** Path relative to the project root. */
  relPath: string;
  status: ScaffoldStatus;
  /** Human-readable reason, shown for skips/updates. */
  detail?: string;
}

/** Outcome of {@link runInit}: one entry per file/edit it considered. */
export interface InitResult {
  actions: ScaffoldAction[];
  /** devDependencies written to package.json that are not installed yet. */
  addedDevDependencies: string[];
  /**
   * Whether the Playwright config tests a production build under E2E_BUILD:
   * `missing-in-scripts` when it does but a kept test:e2e script never sets it.
   */
  buildSwitch: 'on' | 'missing-in-scripts' | 'off';
  /** False when init couldn't tell the dev server's port and left APP_URL to set. */
  isAppUrlKnown: boolean;
}

/** How to build the app and serve the build, and where each server listens. */
export interface BuildServer {
  command: string;
  url: string;
  env: Record<string, string>;
  /** Where `dev` serves the app in the same framework. */
  devUrl: string;
}

// --- file templates (pure renderers) ---------------------------------------

/**
 * Render `test-proxy-recorder.config.ts`. The generated file mirrors the
 * documented config shape: a `defineConfig` default export with the resolved
 * target/port/dir filled in and the optional redaction block left commented out.
 */
export function renderConfig(options: InitOptions): string {
  return `import { defineConfig } from 'test-proxy-recorder';

// Generated by \`test-proxy-recorder init\`.
// Auto-discovered when you run \`test-proxy-recorder\` with no arguments.
// CLI flags always override the values set here.
export default defineConfig({
  // Backend the proxy forwards to: the one your app uses in dev. Point the app's
  // API base URL at the proxy instead; with no test recording or replaying, the
  // proxy passes every request through unchanged.
  target: '${options.target}',

  // Port the proxy listens on. Matches the Playwright client default
  // (override both with the TEST_PROXY_RECORDER_PORT env var).
  port: ${options.port},

  // Where recordings are written, relative to the directory the proxy runs in.
  // Commit this directory — CI replays from it.
  recordingsDir: '${options.dir}',

  // Secrets are redacted automatically (Authorization / Cookie / Set-Cookie).
  // Uncomment to redact extra headers or tokens embedded in bodies.
  // redaction: {
  //   headers: ['x-api-key'],
  //   bodyPatterns: [/sk_live_\\w+/g],
  //   allowCookies: ['theme'],
  // },
});
`;
}

/**
 * Render a fresh `playwright.config.ts` wired to the proxy's control endpoint.
 * `devCommand` starts the app the way `dev` does, or null when there is none.
 */
export function renderPlaywrightConfig(
  options: InitOptions,
  devCommand: string | null,
  devUrl: string | null,
  build: BuildServer | null,
): string {
  const app =
    devCommand && build
      ? renderBuildSwitch(devCommand, build)
      : renderDevServer(devCommand, devUrl);
  return `import { defineConfig } from '@playwright/test';

// Generated by \`test-proxy-recorder init\`.
${app.header}

export default defineConfig({
  testDir: './e2e',
  // Recording runs one test at a time, in order; replay runs them in parallel.
  fullyParallel: !process.env.RECORD_MODE,
  // Resets the proxy to transparent mode after the run.
  globalTeardown: './e2e/global-teardown.ts',
  use: { baseURL: APP_URL },
  // The proxy forwards to your dev backend, so tests use its data and a failure
  // can be reproduced by hand. A server that is already running is reused.
  webServer: [
    // Reads target/port/dir from test-proxy-recorder.config.ts. /__control
    // answers even when the backend is down.
    {
      command: 'test-proxy-recorder',
      url: 'http://localhost:${options.port}/__control',
      reuseExistingServer: true,
      timeout: 15_000,
    },
${app.entry}
  ],
});
`;
}

function renderDevServer(devCommand: string | null, devUrl: string | null) {
  if (devCommand && devUrl) {
    return {
      header: `// The URL your dev server serves the app on.\nconst APP_URL = '${devUrl}';`,
      entry: `${renderDevEntry(devCommand, '    ')},`,
    };
  }
  return {
    header: [
      '// Set APP_URL to the URL your dev server serves the app on, then uncomment',
      '// the app entry in webServer.',
      `const APP_URL = '${PLACEHOLDER_DEV_URL}';`,
    ].join('\n'),
    entry: `${renderDevEntry(devCommand ?? '<your dev command>', '    // ')},`,
  };
}

/** The dev server entry, reused when it already runs. */
function renderDevEntry(devCommand: string, indent: string): string {
  return [
    '{',
    `  command: '${devCommand}',`,
    '  url: APP_URL,',
    '  reuseExistingServer: true,',
    '  // pnpm -r/--parallel runs each package in its own process group, which the',
    '  // default SIGKILL leaves running on its port; on SIGTERM pnpm stops them.',
    "  gracefulShutdown: { signal: 'SIGTERM', timeout: 5_000 },",
    '}',
  ]
    .map((line) => `${indent}${line}`)
    .join('\n');
}

function renderBuildSwitch(devCommand: string, build: BuildServer) {
  const env = Object.entries(build.env)
    .map(([key, value]) => `${key}: '${value}'`)
    .join(', ');
  return {
    header: [
      '// The test:e2e scripts set E2E_BUILD=1 to test a production build, rebuilt',
      '// every run. A plain `playwright test` (or --ui) uses your dev server.',
      'const IS_BUILD = Boolean(process.env.E2E_BUILD);',
      '// The URLs your build and dev servers serve the app on.',
      `const APP_URL = IS_BUILD ? '${build.url}' : '${build.devUrl}';`,
    ].join('\n'),
    entry: [
      '    IS_BUILD',
      `      ? { command: '${build.command}', url: APP_URL, env: { ${env} } }`,
      `      : ${renderDevEntry(devCommand, '        ').trimStart()},`,
    ].join('\n'),
  };
}

/** Render the per-test proxy fixture (`e2e/fixtures.ts`). */
export function renderFixtures(): string {
  return String.raw`import { test as base, type Page } from '@playwright/test';
import { playwrightProxy } from 'test-proxy-recorder';

// External domains the browser calls directly (auth, CDN, analytics, ...),
// e.g. /cognito-.*\.amazonaws\.com/. Calls that go through the proxy, including
// via a dev-server proxy such as Vite's server.proxy, are recorded without it.
// Leave it undefined until you need it: replay loads a HAR for any pattern.
const CLIENT_SIDE_URL: RegExp | undefined = undefined;

// The test:e2e:record script sets RECORD_MODE=1 to hit the real API and rewrite the
// recordings (one worker); without it, tests replay from the committed files.
const MODE = process.env.RECORD_MODE ? 'record' : 'replay';

export const test = base.extend<{ page: Page }>({
  page: async ({ context }, use, testInfo) => {
    const page = await context.newPage();
    await playwrightProxy.before(page, testInfo, MODE, { url: CLIENT_SIDE_URL });
    await use(page);
  },
});

export { expect } from '@playwright/test';
`;
}

/** Render the global teardown (`e2e/global-teardown.ts`). */
export function renderTeardown(): string {
  return `import { playwrightProxy } from 'test-proxy-recorder';

// Runs once after the whole suite — resets the proxy to transparent mode and
// redacts secrets from the recorded .har files (HAR redaction happens here, not
// per-test). Do NOT call teardown() per-test (afterAll): it flips the global
// mode and breaks parallel replay.
export default async function globalTeardown() {
  await playwrightProxy.teardown().catch((err: unknown) => {
    console.warn('test-proxy-recorder teardown', err);
  });
}
`;
}

/** Next.js project info detected from `package.json`, or null when not Next.js. */
export interface NextjsInfo {
  /** Major version parsed from the declared range, or null when not numeric. */
  major: number | null;
}

/** Pull the leading major version out of a semver range (`^16.2.4` → 16). */
function parseMajor(range: string): number | null {
  const match = range.match(/(\d+)/);
  return match ? Number.parseInt(match[1], 10) : null;
}

/**
 * Detect a Next.js project from its declared `next` dependency. Returns the
 * major version (when numeric), or null when the project does not depend on
 * Next.js. Used only to decide whether to wire SSR fetch tagging.
 */
export function detectNextjs(cwd: string): NextjsInfo | null {
  const pkgPath = path.join(cwd, 'package.json');
  if (!existsSync(pkgPath)) return null;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as PackageJson;
    const range = pkg.dependencies?.next ?? pkg.devDependencies?.next;
    if (!range) return null;
    return { major: parseMajor(range) };
  } catch {
    return null;
  }
}

/** Scripts merged into the project's package.json. */
export function scaffoldScripts(
  hasBuildSwitch: boolean,
): Record<string, string> {
  const build = hasBuildSwitch ? 'E2E_BUILD=1 ' : '';
  return {
    proxy: 'test-proxy-recorder',
    'proxy:reset': 'test-proxy-recorder reset',
    'test:e2e': `${build}playwright test`,
    'test:e2e:record': `${build}RECORD_MODE=1 playwright test --workers 1`,
  };
}

/**
 * Inject a `webServer` (pointing at the proxy's control endpoint) and a
 * `globalTeardown` into an existing Playwright config's source. Pure string
 * transform — easy to unit-test and conservative: it bails (rather than risk
 * producing a broken or duplicate-keyed config) when it cannot safely edit.
 */
export function injectProxyIntoConfig(
  source: string,
  options: InitOptions,
): { contents: string; changed: boolean; reason?: string } {
  if (source.includes('test-proxy-recorder')) {
    return {
      contents: source,
      changed: false,
      reason: 'already references test-proxy-recorder',
    };
  }
  // A commented-out block, like the one create-playwright writes, doesn't count.
  const code = source
    .split('\n')
    .filter((line) => !line.trimStart().startsWith('//'))
    .join('\n');
  if (/\bwebServer\s*:/.test(code)) {
    return {
      contents: source,
      changed: false,
      reason: 'already defines webServer — add the proxy command manually',
    };
  }

  // Insert right after the config object opens: `defineConfig({` or a bare
  // `export default {`.
  const opener =
    source.match(/defineConfig\s*\(\s*\{/) ??
    source.match(/export\s+default\s*\{/);
  if (opener?.index === undefined) {
    return {
      contents: source,
      changed: false,
      reason: 'could not locate the config object',
    };
  }

  const hasTeardown = /\bglobalTeardown\s*:/.test(source);
  const teardownLine = hasTeardown
    ? ''
    : `\n  globalTeardown: './e2e/global-teardown.ts',`;
  const block =
    `\n  // Added by test-proxy-recorder init` +
    `\n  webServer: {` +
    `\n    command: 'test-proxy-recorder',` +
    `\n    url: 'http://localhost:${options.port}/__control',` +
    `\n    reuseExistingServer: true,` +
    `\n    timeout: 15_000,` +
    `\n  },${teardownLine}`;

  const at = opener.index + opener[0].length;
  const contents = source.slice(0, at) + block + source.slice(at);
  return { contents, changed: true };
}

// --- filesystem orchestration ----------------------------------------------

/** Locate an existing Playwright config in `cwd`, or null when none exists. */
export function findPlaywrightConfig(cwd: string): string | null {
  for (const name of PLAYWRIGHT_CONFIG_NAMES) {
    const candidate = path.join(cwd, name);
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

/**
 * Write `contents` to `relPath` under `cwd`, creating parent dirs. Existing
 * files are left untouched unless `force` is set, so re-running `init` is safe.
 */
function writeFile(
  cwd: string,
  relPath: string,
  contents: string,
  force: boolean,
): ScaffoldAction {
  const absPath = path.join(cwd, relPath);
  const overwritten = existsSync(absPath);
  if (overwritten && !force) {
    return { relPath, status: 'skipped', detail: 'already exists' };
  }
  mkdirSync(path.dirname(absPath), { recursive: true });
  writeFileSync(absPath, contents, 'utf8');
  return {
    relPath,
    status: 'created',
    detail: overwritten ? 'overwritten' : undefined,
  };
}

/**
 * Wire Playwright up: edit an existing config in place, or write a fresh default
 * one when none exists. Never touches a config it cannot safely edit.
 */
function scaffoldPlaywright(
  cwd: string,
  options: InitOptions,
  build: BuildServer | null,
): ScaffoldAction {
  const existing = findPlaywrightConfig(cwd);
  if (!existing) {
    return writeFile(
      cwd,
      'playwright.config.ts',
      renderPlaywrightConfig(
        options,
        getAppDevCommand(cwd),
        getDevUrl(cwd),
        build,
      ),
      options.force,
    );
  }

  const relPath = path.relative(cwd, existing) || path.basename(existing);
  const source = readFileSync(existing, 'utf8');
  const { contents, changed, reason } = injectProxyIntoConfig(source, options);
  if (!changed) {
    return { relPath, status: 'skipped', detail: reason };
  }
  writeFileSync(existing, contents, 'utf8');
  return {
    relPath,
    status: 'updated',
    detail: 'added webServer + globalTeardown',
  };
}

/** App Router root-layout files Next.js recognizes, in resolution order. */
const NEXT_LAYOUT_NAMES = [
  'app/layout.tsx',
  'app/layout.jsx',
  'app/layout.js',
  'src/app/layout.tsx',
  'src/app/layout.jsx',
  'src/app/layout.js',
];

/** True when an action concerns the Next.js root layout. */
export function isNextLayoutAction(action: ScaffoldAction): boolean {
  return action.relPath.includes('layout.');
}

/** Find the App Router root layout, or null when none exists. */
function findRootLayout(cwd: string): string | null {
  for (const name of NEXT_LAYOUT_NAMES) {
    if (existsSync(path.join(cwd, name.split('/').join(path.sep)))) return name;
  }
  return null;
}

/**
 * Inject `registerProxyFetch()` into a root layout's source — an import plus a
 * top-level call placed after the import block — so server-side fetches carry
 * the recording-session header. Pure string transform; conservative: bails
 * (rather than risk a broken file) when it can't find an import to anchor to or
 * the file is a client component.
 */
export function injectRegisterProxyFetch(source: string): {
  contents: string;
  changed: boolean;
  reason?: string;
} {
  if (source.includes('registerProxyFetch')) {
    return {
      contents: source,
      changed: false,
      reason: 'already calls registerProxyFetch',
    };
  }
  if (/^\s*['"]use client['"]/.test(source)) {
    return {
      contents: source,
      changed: false,
      reason: "root layout is a client component ('use client')",
    };
  }

  // End index of the last top-level import (`import x from 'y'` or `import 'y'`).
  // One pattern covers both: anything up to the module specifier, then `'…'`.
  // Anchored to the start of a line (so it only matches statements, not an
  // `import` mid-expression) and with a negative lookahead that rejects dynamic
  // `import(...)` calls and `import.meta` — a bare `import('x')` is an
  // expression, not a statement we can safely anchor an insertion after.
  const importRe = /^[ \t]*import\b(?!\s*[(.])[^;'"]*['"][^'"]+['"];?/gm;
  let lastEnd = -1;
  for (const match of source.matchAll(importRe)) {
    if (match.index !== undefined) lastEnd = match.index + match[0].length;
  }
  if (lastEnd === -1) {
    return {
      contents: source,
      changed: false,
      reason: 'could not find an import to anchor to',
    };
  }

  const block =
    `\nimport { registerProxyFetch } from 'test-proxy-recorder/nextjs';` +
    `\n\n// Added by test-proxy-recorder init. Tags server-side fetches with the` +
    `\n// current test's recording-session id so the proxy attributes SSR requests` +
    `\n// to the right test. No-op in production unless TEST_PROXY_RECORDER_ENABLED` +
    `\n// is set. Record against a production build (next build && next start) —` +
    `\n// the next dev server can reset this fetch patch.` +
    `\nregisterProxyFetch();`;
  const contents = source.slice(0, lastEnd) + block + source.slice(lastEnd);
  return { contents, changed: true };
}

/**
 * Wire Next.js SSR fetch tagging by injecting `registerProxyFetch()` into the
 * root layout. Conservative: when there is no layout, or it can't be safely
 * edited, it skips and the next-steps output tells the user the one line to add.
 * (The middleware/`proxy.ts` approach also works but is optional — see the docs.)
 */
function scaffoldRegisterProxyFetch(cwd: string): ScaffoldAction {
  const rel = findRootLayout(cwd);
  if (!rel) {
    return {
      relPath: 'app/layout.tsx',
      status: 'skipped',
      detail: 'no root layout found — add registerProxyFetch() yourself',
    };
  }
  const abs = path.join(cwd, rel.split('/').join(path.sep));
  const source = readFileSync(abs, 'utf8');
  const { contents, changed, reason } = injectRegisterProxyFetch(source);
  if (!changed) {
    return { relPath: rel, status: 'skipped', detail: reason };
  }
  writeFileSync(abs, contents, 'utf8');
  return {
    relPath: rel,
    status: 'updated',
    detail: 'added registerProxyFetch()',
  };
}

/** Detect the indentation used by an existing JSON file (defaults to 2 spaces). */
function detectIndent(source: string): string {
  const match = source.match(/\n([ \t]+)"/);
  return match ? match[1] : '  ';
}

/** Script the original `dev` command is moved to when wrapping it. */
const DEV_APP_SCRIPT = 'dev:app';

/** How a package manager runs a named script (`pnpm proxy`, `npm run proxy`). */
function runScriptPrefix(pm: PackageManager): string {
  // pnpm/yarn run scripts as `pnpm <script>`; npm/bun need `run`.
  return pm === 'pnpm' || pm === 'yarn' ? pm : `${pm} run`;
}

/**
 * Apply `scripts` onto `existing` in place, honouring `force`. Returns which
 * keys were newly added and which were left as the user already had them.
 */
function mergeScripts(
  existing: Record<string, string>,
  scripts: Record<string, string>,
  force: boolean,
): { added: string[]; skipped: string[] } {
  const added: string[] = [];
  const skipped: string[] = [];
  for (const [name, command] of Object.entries(scripts)) {
    const conflicts = existing[name] !== undefined && !force;
    (conflicts ? skipped : added).push(name);
    if (!conflicts) existing[name] = command;
  }
  return { added, skipped };
}

/**
 * Wrap an existing `dev` script so it runs the proxy alongside the app: the
 * original command is moved to `dev:app` and `dev` becomes a `concurrently`
 * invocation. Idempotent and conservative — does nothing when there is no `dev`
 * script, when it already runs the proxy, or when `dev:app` is taken.
 */
function wrapDevScript(
  scripts: Record<string, string>,
  pm: PackageManager,
): boolean {
  const dev = scripts.dev;
  if (dev === undefined) return false;
  if (dev.includes('test-proxy-recorder') || dev.includes('concurrently')) {
    return false;
  }
  if (scripts[DEV_APP_SCRIPT] !== undefined) return false;

  const run = runScriptPrefix(pm);
  scripts[DEV_APP_SCRIPT] = dev;
  scripts.dev = `concurrently --kill-others "${run} proxy" "${run} ${DEV_APP_SCRIPT}"`;
  return true;
}

function readPackageScripts(cwd: string): Record<string, string> {
  const pkgPath = path.join(cwd, 'package.json');
  if (!existsSync(pkgPath)) return {};
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as PackageJson;
  return pkg.scripts ?? {};
}

/**
 * The command that starts the app without the proxy: `dev:app` once `dev` is
 * wrapped, since the Playwright config starts the proxy on its own.
 */
function getAppDevCommand(cwd: string): string | null {
  const scripts = readPackageScripts(cwd);
  const run = runScriptPrefix(detectPackageManager(cwd));
  if (scripts[DEV_APP_SCRIPT] !== undefined) return `${run} ${DEV_APP_SCRIPT}`;
  if (
    scripts.dev === undefined ||
    scripts.dev.includes('test-proxy-recorder')
  ) {
    return null;
  }
  return `${run} dev`;
}

const PORT_FLAG = /(?:--port[ =]|-p\s+)(\d+)/;

/** The program a script runs, past any leading `NAME=value` assignments. */
function getProgram(command: string): string | undefined {
  return command.split(/\s+/).find((word) => word && !word.includes('='));
}

/**
 * Where the app's own dev command serves it: a port set in the command, else
 * the default of the dev server it runs. Null when neither tells.
 */
function getDevUrl(cwd: string): string | null {
  const scripts = readPackageScripts(cwd);
  // Once `dev` is wrapped, the app's own command is in dev:app.
  const dev = scripts[DEV_APP_SCRIPT] ?? scripts.dev;
  if (dev === undefined) return null;
  const port =
    PORT_FLAG.exec(dev)?.[1] ?? DEV_PORT_BY_COMMAND[getProgram(dev) ?? ''];
  return port === undefined ? null : `http://localhost:${port}`;
}

/**
 * How to serve the build with `preview`, or null when it doesn't run Vite.
 * Vite's port is passed explicitly: TanStack Start's Nitro plugin moves it to 3000.
 */
function getPreviewServer(
  preview: string,
  pm: PackageManager,
): { command: string; url: string } | null {
  const run = runScriptPrefix(pm);
  const ownPort = PORT_FLAG.exec(preview)?.[1];
  if (ownPort !== undefined) {
    return {
      command: `${run} build && ${run} preview`,
      url: `http://localhost:${ownPort}`,
    };
  }
  if (getProgram(preview) !== 'vite') return null;
  // npm passes arguments on to the script only after `--`.
  const separator = pm === 'npm' ? ' --' : '';
  return {
    command: `${run} build && ${run} preview${separator} --port ${VITE_PREVIEW_PORT}`,
    url: `http://localhost:${VITE_PREVIEW_PORT}`,
  };
}

/**
 * Build and serve commands from the project's own scripts: a Vite `preview`,
 * or Next.js `start` on its own port. Null when there is no dev server to fall
 * back to or neither is safe to guess.
 */
function getBuildServer(cwd: string): BuildServer | null {
  const { build, preview, start } = readPackageScripts(cwd);
  const devUrl = getDevUrl(cwd);
  if (build === undefined || devUrl === null) return null;
  const pm = detectPackageManager(cwd);
  const run = runScriptPrefix(pm);
  // The documented switch that points the app's API base URL at the proxy.
  const env = { TEST_PROXY_RECORDER_ENABLED: 'true' };
  const previewServer =
    preview === undefined ? null : getPreviewServer(preview, pm);
  if (previewServer !== null && previewServer.url !== devUrl) {
    return { ...previewServer, env, devUrl };
  }
  // A start script that sets its own port would ignore PORT.
  if (!detectNextjs(cwd) || start === undefined || PORT_FLAG.test(start)) {
    return null;
  }
  return {
    command: `${run} build && ${run} start`,
    url: `http://localhost:${NEXT_BUILD_PORT}`,
    env: { ...env, PORT: NEXT_BUILD_PORT },
    devUrl,
  };
}

/** Add `concurrently` as a devDependency when the project lacks it. */
function ensureConcurrentlyDep(pkg: {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}): boolean {
  if (
    pkg.dependencies?.concurrently !== undefined ||
    pkg.devDependencies?.concurrently !== undefined
  ) {
    return false;
  }
  pkg.devDependencies ??= {};
  pkg.devDependencies.concurrently = '^9.0.0';
  return true;
}

interface PackageJson {
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

/**
 * Merge the scaffold scripts into an existing package.json without clobbering
 * existing keys (unless `force`), and wrap the project's `dev` script so it runs
 * the proxy too. When there is no package.json — e.g. the user has not
 * initialized one yet — the edit is skipped rather than inventing one.
 */
function updatePackageScripts(
  cwd: string,
  scripts: Record<string, string>,
  force: boolean,
): { action: ScaffoldAction; addedDevDependencies: string[] } {
  const relPath = 'package.json';
  const absPath = path.join(cwd, relPath);

  if (!existsSync(absPath)) {
    return {
      action: { relPath, status: 'skipped', detail: 'no package.json found' },
      addedDevDependencies: [],
    };
  }

  const source = readFileSync(absPath, 'utf8');
  const pkg = JSON.parse(source) as PackageJson;
  pkg.scripts ??= {};

  const { added, skipped } = mergeScripts(pkg.scripts, scripts, force);
  const devWrapped = wrapDevScript(pkg.scripts, detectPackageManager(cwd));
  const addedDevDependencies =
    devWrapped && ensureConcurrentlyDep(pkg) ? ['concurrently'] : [];

  if (added.length === 0 && !devWrapped) {
    return {
      action: {
        relPath,
        status: 'skipped',
        detail: `scripts already present (${skipped.join(', ')})`,
      },
      addedDevDependencies,
    };
  }

  const indent = detectIndent(source);
  const trailingNewline = source.endsWith('\n') ? '\n' : '';
  writeFileSync(absPath, JSON.stringify(pkg, null, indent) + trailingNewline);

  return {
    action: {
      relPath,
      status: 'updated',
      detail: describeEdit(added, skipped, devWrapped),
    },
    addedDevDependencies,
  };
}

/** Build the human-readable summary of a package.json edit. */
function describeEdit(
  added: string[],
  skipped: string[],
  devWrapped: boolean,
): string {
  const parts: string[] = [];
  if (added.length > 0) parts.push(`added ${added.join(', ')}`);
  if (skipped.length > 0) parts.push(`kept existing ${skipped.join(', ')}`);
  if (devWrapped) parts.push(`wrapped dev (original → ${DEV_APP_SCRIPT})`);
  return parts.join('; ');
}

/**
 * Run the full scaffold: config file, Playwright config (created or edited in
 * place), e2e fixture + teardown, and package.json scripts. Pure filesystem work
 * — the optional Playwright CLI install lives in {@link initCommand}. Every step
 * is non-destructive.
 */
export function runInit(
  options: InitOptions,
  cwd: string = process.cwd(),
): InitResult {
  // An existing Playwright config is only patched, so it gets no new build
  // switch; one an earlier run wrote keeps its scripts setting E2E_BUILD.
  const existingConfig = findPlaywrightConfig(cwd);
  const build = existingConfig ? null : getBuildServer(cwd);
  const hasConfigSwitch = existingConfig
    ? readFileSync(existingConfig, 'utf8').includes('process.env.E2E_BUILD')
    : build !== null;
  const packageEdit = updatePackageScripts(
    cwd,
    scaffoldScripts(hasConfigSwitch),
    options.force,
  );
  const actions: ScaffoldAction[] = [
    writeFile(cwd, CONFIG_FILENAME, renderConfig(options), options.force),
    scaffoldPlaywright(cwd, options, build),
    writeFile(cwd, 'e2e/fixtures.ts', renderFixtures(), options.force),
    writeFile(cwd, 'e2e/global-teardown.ts', renderTeardown(), options.force),
    packageEdit.action,
  ];

  // Next.js makes server-side fetches that need the recording-session header.
  // Wire it by injecting registerProxyFetch() into the root layout when we
  // detect Next.js. (The middleware/proxy.ts approach also works but is optional.)
  if (detectNextjs(cwd)) {
    actions.push(scaffoldRegisterProxyFetch(cwd));
  }

  return {
    actions,
    addedDevDependencies: packageEdit.addedDevDependencies,
    buildSwitch: getBuildSwitch(cwd, hasConfigSwitch),
    isAppUrlKnown: existingConfig !== null || getDevUrl(cwd) !== null,
  };
}

function getBuildSwitch(
  cwd: string,
  hasConfigSwitch: boolean,
): InitResult['buildSwitch'] {
  if (!hasConfigSwitch) return 'off';
  const testScript = readPackageScripts(cwd)['test:e2e'] ?? '';
  return testScript.includes('E2E_BUILD=1') ? 'on' : 'missing-in-scripts';
}

// --- Playwright CLI install (side-effecting) -------------------------------

/** True when `@playwright/test` is installed or declared in the project. */
export function playwrightInstalled(cwd: string): boolean {
  if (existsSync(path.join(cwd, 'node_modules', '@playwright', 'test'))) {
    return true;
  }
  const pkgPath = path.join(cwd, 'package.json');
  if (!existsSync(pkgPath)) return false;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    return Boolean(
      pkg.dependencies?.['@playwright/test'] ??
        pkg.devDependencies?.['@playwright/test'],
    );
  } catch {
    return false;
  }
}

type PackageManager = 'pnpm' | 'yarn' | 'bun' | 'npm';

/** Best-effort package-manager detection from the env / lockfiles. */
export function detectPackageManager(cwd: string): PackageManager {
  const ua = process.env.npm_config_user_agent ?? '';
  if (ua.startsWith('pnpm') || existsSync(path.join(cwd, 'pnpm-lock.yaml'))) {
    return 'pnpm';
  }
  if (ua.startsWith('yarn') || existsSync(path.join(cwd, 'yarn.lock'))) {
    return 'yarn';
  }
  if (ua.startsWith('bun') || existsSync(path.join(cwd, 'bun.lockb'))) {
    return 'bun';
  }
  return 'npm';
}

interface ShellCommand {
  cmd: string;
  args: string[];
}

/** The arguments that add one devDependency with the project's package manager. */
function addDevDependencyArgs(
  pm: PackageManager,
  cwd: string,
  name: string,
): string[] {
  switch (pm) {
    case 'pnpm': {
      // pnpm refuses a plain `add` at a workspace root (ERR_PNPM_ADDING_TO_ROOT).
      const isWorkspaceRoot = existsSync(path.join(cwd, 'pnpm-workspace.yaml'));
      return ['add', '-D', ...(isWorkspaceRoot ? ['-w'] : []), name];
    }
    case 'yarn': {
      return ['add', '-D', name];
    }
    case 'bun': {
      return ['add', '-d', name];
    }
    default: {
      return ['install', '-D', name];
    }
  }
}

/** The command that adds one devDependency with the project's package manager. */
export function addDevDependencyCommand(
  pm: PackageManager,
  cwd: string,
  name: string,
): string {
  return [pm, ...addDevDependencyArgs(pm, cwd, name)].join(' ');
}

const BIN_RUNNER: Record<PackageManager, ShellCommand> = {
  pnpm: { cmd: 'pnpm', args: ['exec'] },
  yarn: { cmd: 'yarn', args: [] },
  bun: { cmd: 'bunx', args: [] },
  npm: { cmd: 'npx', args: [] },
};

/**
 * Add `@playwright/test` and download Chromium. Not `create playwright`: its
 * config (testDir ./tests) and example tests clash with the ones init writes.
 */
export function playwrightInstallCommands(
  pm: PackageManager,
  cwd: string,
): ShellCommand[] {
  const runner = BIN_RUNNER[pm];
  return [
    { cmd: pm, args: addDevDependencyArgs(pm, cwd, '@playwright/test') },
    {
      cmd: runner.cmd,
      args: [...runner.args, 'playwright', 'install', 'chromium'],
    },
  ];
}

/** Install Playwright when it is missing. Best-effort: a failure prints the command. */
function maybeInstallPlaywright(options: InitOptions, cwd: string): void {
  if (!options.install || playwrightInstalled(cwd)) return;

  const pm = detectPackageManager(cwd);
  console.log(
    'Playwright is not installed. Installing @playwright/test and Chromium (pass --no-install to skip)...',
  );
  const isInstalled = playwrightInstallCommands(pm, cwd).every(
    ({ cmd, args }) => runCommand(cmd, args, cwd),
  );
  if (!isInstalled) {
    console.warn(
      'Playwright install did not complete. Install it with ' +
        `\`${addDevDependencyCommand(pm, cwd, '@playwright/test')}\`.`,
    );
  }
}

/** Run a command in `cwd` with inherited output; true when it exits with 0. */
function runCommand(cmd: string, args: string[], cwd: string): boolean {
  // npm, pnpm and npx are .cmd scripts on Windows, which only a shell can start;
  // the arguments are init's own, so joining them into one line is safe.
  const isWindows = process.platform === 'win32';
  try {
    const result = isWindows
      ? // eslint-disable-next-line sonarjs/os-command -- fixed commands, no user input
        spawnSync([cmd, ...args].join(' '), {
          cwd,
          stdio: 'inherit',
          shell: true,
        })
      : spawnSync(cmd, args, { cwd, stdio: 'inherit' });
    return result.status === 0;
  } catch {
    return false;
  }
}

/**
 * Install the devDependencies init just wrote to package.json, so the wrapped
 * `dev` script runs. Returns whether they are installed; a skipped or failed
 * install leaves the command in the printed next steps.
 */
function installAddedDependencies(
  options: InitOptions,
  cwd: string,
  added: string[],
): boolean {
  if (added.length === 0) return true;
  if (!options.install) return false;

  const pm = detectPackageManager(cwd);
  console.log(
    `Added ${added.join(', ')} to devDependencies. ` +
      `Running \`${pm} install\` (pass --no-install to skip)...`,
  );
  return runCommand(pm, ['install'], cwd);
}

// --- CLI wiring ------------------------------------------------------------

/**
 * Parse `init` subcommand arguments. `argv` is the raw process argv with the
 * leading `node`, script, and `init` token already removed by the caller.
 */
export function parseInitArgs(argv: string[]): InitOptions {
  const program = new Command();

  program
    .name('test-proxy-recorder init')
    .description(
      'Scaffold test-proxy-recorder config + Playwright setup in the current directory',
    )
    .argument(
      '[target]',
      'Backend API URL your app uses in dev; the proxy forwards to it',
      DEFAULT_TARGET,
    )
    .option('-p, --port <number>', 'Proxy port', String(DEFAULT_PROXY_PORT))
    .option('-d, --dir <path>', 'Recordings directory', DEFAULT_DIR)
    .option(
      '-f, --force',
      'Overwrite existing files and package.json scripts',
      false,
    )
    .option(
      '--no-install',
      'Do not run the package manager (Playwright CLI, installing added devDependencies)',
    )
    .allowExcessArguments(false);

  // `argv` is already stripped to the init-specific tokens; tell commander to
  // treat it as user args (no node/script prefix to skip).
  program.parse(argv, { from: 'user' });

  const target = program.args[0] ?? DEFAULT_TARGET;
  const opts = program.opts<{
    port: string;
    dir: string;
    force: boolean;
    install: boolean;
  }>();

  const port = Number.parseInt(opts.port, 10);
  if (Number.isNaN(port) || port < 1025 || port > 65_535) {
    console.error('Error: Invalid port number. Must be between 1025 and 65535');
    process.exit(1);
  }

  return {
    target,
    port,
    dir: opts.dir,
    force: opts.force,
    install: opts.install,
  };
}

/** Past-tense label shown for each action in the summary. */
const STATUS_LABEL: Record<ScaffoldStatus, string> = {
  created: 'Created',
  updated: 'Updated',
  skipped: 'Skipped',
};

/**
 * Entry point for the `init` subcommand: optionally bootstrap Playwright, run the
 * scaffold, and print a per-file summary plus next steps. A thin, side-effecting
 * shell over the testable `parseInitArgs` / `runInit` pieces.
 */
export function initCommand(argv: string[], cwd: string = process.cwd()): void {
  const options = parseInitArgs(argv);

  maybeInstallPlaywright(options, cwd);

  const { actions, addedDevDependencies, buildSwitch, isAppUrlKnown } = runInit(
    options,
    cwd,
  );
  const isInstalled = installAddedDependencies(
    options,
    cwd,
    addedDevDependencies,
  );

  console.log('');
  for (const action of actions) {
    const label = STATUS_LABEL[action.status];
    const suffix = action.detail ? ` — ${action.detail}` : '';
    console.log(`${label.padEnd(7)} ${action.relPath}${suffix}`);
  }

  printNextSteps(
    actions,
    options,
    isInstalled ? [] : addedDevDependencies,
    detectPackageManager(cwd),
  );
  for (const line of getAppServerLines(buildSwitch, isAppUrlKnown)) {
    console.log(line);
  }
  printAgentPrompt(options);
}

/**
 * Render the copy-pasteable prompt for an AI coding agent to finish the
 * app-specific wiring `init` can't do. The text is the canonical, validated
 * prompt in `agent-prompt.md` (shipped beside this module — see the build's
 * onSuccess copy and the package `files` allowlist); we just fill in the
 * resolved proxy URL, backend target, and recordings dir.
 */
export function renderAgentPrompt(options: InitOptions): string {
  const template = readFileSync(
    new URL('agent-prompt.md', import.meta.url),
    'utf8',
  );
  return template
    .replaceAll('{{PROXY_URL}}', `http://localhost:${options.port}`)
    .replaceAll('{{TARGET}}', options.target)
    .replaceAll('{{DIR}}', options.dir)
    .trimEnd();
}

/** Print the AI-agent recommendation and the tailored prompt. */
function printAgentPrompt(options: InitOptions): void {
  console.log('');
  console.log(
    '🤖 Recommended: finish setup with an AI coding agent (Claude Code, Cursor, …).',
  );
  console.log(
    '   It wires the app-specific bits init can’t guess. Paste this prompt:',
  );
  console.log('');
  console.log('────────────────────────────────────────────────────────');
  console.log(renderAgentPrompt(options));
  console.log('────────────────────────────────────────────────────────');
}

/**
 * The one thing `init` can't do for you: route the app's backend calls through
 * the proxy, in dev/test only. Which env var the app reads, and how to scope it
 * to dev, is app-specific — so we print concrete, copy-pasteable guidance.
 */
function backendPointingLines(
  options: InitOptions,
  devWrapped: boolean,
): string[] {
  const proxyUrl = `http://localhost:${options.port}`;
  const lines = [
    "  1. Point your app's backend calls at the proxy — in dev/test only, never in production.",
    `     Set whatever env var your app reads its API base URL from to:  ${proxyUrl}`,
    `     (it talks to ${options.target} directly today; the proxy forwards there while`,
    '      recording and serves recordings on replay.)',
  ];
  const example = devWrapped
    ? `       "dev:app": "API_BASE_URL=${proxyUrl} <your dev command>"`
    : `       API_BASE_URL=${proxyUrl} <your dev/start command>`;
  lines.push(
    '     e.g. (use cross-env to make this work on Windows):',
    example,
  );
  return lines;
}

/**
 * Lines describing the Next.js SSR wiring outcome: a confirmation when we
 * injected `registerProxyFetch()` into the root layout, or the one line to add
 * by hand when we couldn't.
 */
function registerProxyFetchLines(actions: ScaffoldAction[]): string[] {
  const layout = actions.find((a) => isNextLayoutAction(a));
  if (!layout) return [];
  if (layout.status === 'updated') {
    return [
      `  • Next.js SSR fetch tagging wired into ${layout.relPath} via registerProxyFetch() (no-op in production).`,
      '     Record against a production build (next build && next start, on the same port so Playwright reuses it), not next dev.',
    ];
  }
  return [
    `  • Next.js: add SSR fetch tagging to your root layout (${layout.detail}):`,
    "       import { registerProxyFetch } from 'test-proxy-recorder/nextjs';",
    '       registerProxyFetch(); // top-level in app/layout.tsx — no-op in production',
    '       Using axios for SSR? call registerProxyAxios(yourInstance) instead. Record with build+start, not next dev.',
  ];
}

function getAppServerLines(
  buildSwitch: InitResult['buildSwitch'],
  isAppUrlKnown: boolean,
): string[] {
  const lines: string[] = [];
  if (!isAppUrlKnown) {
    lines.push(
      "  • Set APP_URL in playwright.config.ts to your dev server's URL and uncomment the app entry: init couldn't tell its port.",
    );
  }
  if (buildSwitch === 'on') {
    lines.push(
      '  • test:e2e and test:e2e:record test a production build (E2E_BUILD=1). A plain `playwright test` or `--ui` uses your dev server, to reproduce a failure by hand.',
    );
  }
  if (buildSwitch === 'missing-in-scripts') {
    lines.push(
      '  • playwright.config.ts tests a production build when E2E_BUILD is set, but your existing test:e2e scripts were kept; prefix them with E2E_BUILD=1 to use it.',
    );
  }
  return lines;
}

/** Print the "Next steps" block, tailored to what the scaffold actually did. */
function printNextSteps(
  actions: ScaffoldAction[],
  options: InitOptions,
  uninstalledDependencies: string[],
  pm: PackageManager,
): void {
  const pkgAction = actions.find((a) => a.relPath === 'package.json');
  const pwAction = actions.find((a) =>
    a.relPath.startsWith('playwright.config'),
  );
  const devWrapped = pkgAction?.detail?.includes('wrapped dev') ?? false;

  const step2 =
    pwAction?.status === 'skipped'
      ? `  2. Wire the proxy into your Playwright config (${pwAction.detail}):\n` +
        `       webServer: { command: 'test-proxy-recorder', url: 'http://localhost:${options.port}/__control', reuseExistingServer: true }`
      : '  2. Record: start `dev` (the proxy forwards to your dev backend), put your dev database in the state the tests expect (your own seed script), then run the test:e2e:record script (RECORD_MODE=1, one worker).';

  const step3 =
    pkgAction?.detail === 'no package.json found'
      ? '  3. Add scripts manually: "proxy": "test-proxy-recorder", "test:e2e": "playwright test".'
      : `  3. Commit ${options.dir}; test:e2e replays from it with the backend off.`;

  console.log('');
  console.log('Next steps:');
  if (uninstalledDependencies.length > 0) {
    console.log(
      `  0. Run \`${pm} install\`: init added ${uninstalledDependencies.join(', ')} to devDependencies, and \`${pm} run dev\` fails until it is installed.`,
    );
  }
  for (const line of backendPointingLines(options, devWrapped)) {
    console.log(line);
  }
  console.log(step2);
  console.log(step3);
  for (const line of registerProxyFetchLines(actions)) {
    console.log(line);
  }
  console.log(
    '  • Stuck in record/replay after an interrupted run? Run `test-proxy-recorder reset` (or `proxy:reset`) to return the proxy to transparent mode.',
  );
  console.log(
    '  • The test:e2e scripts set env vars as `NAME=1 command`, which Windows cmd and PowerShell reject (WSL and Git Bash are fine). There, prefix them with cross-env: `cross-env RECORD_MODE=1 playwright test --workers 1`.',
  );
  if (devWrapped) {
    console.log(
      `  • \`dev\` now runs the proxy and your app together through \`concurrently\`; your original command is \`${DEV_APP_SCRIPT}\`.`,
    );
    console.log(
      `     With no test recording or replaying, the proxy forwards everything to ${options.target} unchanged, so dev works as before.`,
    );
  }
}
